create table "public"."campaigns" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "seller" uuid,
    "rewards" jsonb
);


alter table "public"."campaigns" enable row level security;

alter table "public"."users" alter column "type" set data type text using "type"::text;

CREATE UNIQUE INDEX rewards_pkey ON public.campaigns USING btree (id);

alter table "public"."campaigns" add constraint "rewards_pkey" PRIMARY KEY using index "rewards_pkey";

alter table "public"."campaigns" add constraint "rewards_seller_fkey" FOREIGN KEY (seller) REFERENCES users(id) not valid;

alter table "public"."campaigns" validate constraint "rewards_seller_fkey";

grant delete on table "public"."campaigns" to "anon";

grant insert on table "public"."campaigns" to "anon";

grant references on table "public"."campaigns" to "anon";

grant select on table "public"."campaigns" to "anon";

grant trigger on table "public"."campaigns" to "anon";

grant truncate on table "public"."campaigns" to "anon";

grant update on table "public"."campaigns" to "anon";

grant delete on table "public"."campaigns" to "authenticated";

grant insert on table "public"."campaigns" to "authenticated";

grant references on table "public"."campaigns" to "authenticated";

grant select on table "public"."campaigns" to "authenticated";

grant trigger on table "public"."campaigns" to "authenticated";

grant truncate on table "public"."campaigns" to "authenticated";

grant update on table "public"."campaigns" to "authenticated";

grant delete on table "public"."campaigns" to "service_role";

grant insert on table "public"."campaigns" to "service_role";

grant references on table "public"."campaigns" to "service_role";

grant select on table "public"."campaigns" to "service_role";

grant trigger on table "public"."campaigns" to "service_role";

grant truncate on table "public"."campaigns" to "service_role";

grant update on table "public"."campaigns" to "service_role";



