alter table "public"."campaigns" drop constraint "campaigns_user_id_fkey";

create table "public"."videos" (
    "id" bigint generated by default as identity not null,
    "seller_id" uuid,
    "video_id" text,
    "title" text,
    "product_id" text,
    "creator_username" text,
    "post_time" text,
    "views" numeric,
    "sku_orders" numeric,
    "units_sold" numeric,
    "click_through_rate" numeric,
    "gmv" numeric
);


alter table "public"."videos" enable row level security;

alter table "public"."campaigns" drop column "user_id";

alter table "public"."campaigns" add column "seller_id" uuid;

CREATE UNIQUE INDEX videos_pkey ON public.videos USING btree (id);

CREATE UNIQUE INDEX videos_video_id_key ON public.videos USING btree (video_id);

alter table "public"."videos" add constraint "videos_pkey" PRIMARY KEY using index "videos_pkey";

alter table "public"."campaigns" add constraint "campaigns_seller_id_fkey" FOREIGN KEY (seller_id) REFERENCES users(id) not valid;

alter table "public"."campaigns" validate constraint "campaigns_seller_id_fkey";

alter table "public"."videos" add constraint "videos_seller_id_fkey" FOREIGN KEY (seller_id) REFERENCES users(id) not valid;

alter table "public"."videos" validate constraint "videos_seller_id_fkey";

alter table "public"."videos" add constraint "videos_video_id_key" UNIQUE using index "videos_video_id_key";

grant delete on table "public"."videos" to "anon";

grant insert on table "public"."videos" to "anon";

grant references on table "public"."videos" to "anon";

grant select on table "public"."videos" to "anon";

grant trigger on table "public"."videos" to "anon";

grant truncate on table "public"."videos" to "anon";

grant update on table "public"."videos" to "anon";

grant delete on table "public"."videos" to "authenticated";

grant insert on table "public"."videos" to "authenticated";

grant references on table "public"."videos" to "authenticated";

grant select on table "public"."videos" to "authenticated";

grant trigger on table "public"."videos" to "authenticated";

grant truncate on table "public"."videos" to "authenticated";

grant update on table "public"."videos" to "authenticated";

grant delete on table "public"."videos" to "service_role";

grant insert on table "public"."videos" to "service_role";

grant references on table "public"."videos" to "service_role";

grant select on table "public"."videos" to "service_role";

grant trigger on table "public"."videos" to "service_role";

grant truncate on table "public"."videos" to "service_role";

grant update on table "public"."videos" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."videos"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read for authenticated users only"
on "public"."videos"
as permissive
for select
to authenticated
using (true);




