create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "create_time" numeric,
    "campaign_id" text,
    "order_id" text,
    "video_id" text,
    "product_id" text,
    "creator_username" text,
    "commission_base" numeric,
    "paid_commission" numeric,
    "quantity" bigint,
    "status" text
);


alter table "public"."orders" enable row level security;

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."orders" add constraint "orders_campaign_id_fkey" FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) not valid;

alter table "public"."orders" validate constraint "orders_campaign_id_fkey";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."orders"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read for authenticated users only"
on "public"."orders"
as permissive
for select
to authenticated
using (true);




